let foods;
export default foods = [
	{"name": "Bamboo shoots", "score": 1},
	{"name": "Brussels sprouts", "score": 1},
	{"name": "Cabbage (green or white)", "score": 1},
	{"name": "Celery", "score": 1},
	{"name": "Chives", "score": 1},
	{"name": "Choko", "score": 1},
	{"name": "Beans (dried - not borlotti)", "score": 1},
	{"name": "Peas (dried)", "score": 1},
	{"name": "Leek", "score": 1},
	{"name": "Lentils (brown or red)", "score": 1},
	{"name": "Iceberg lettuce", "score": 1},
	{"name": "Mungbean (and spouts)", "score": 1},
	{"name": "Potato (peeled white)", "score": 1},
	{"name": "Eschallots", "score": 1},
	{"name": "Swedes", "score": 1},
	{"name": "Soybeans", "score": 1},
	{"name": "Beansprouts", "score": 1},
	{"name": "Green Split peas", "score": 1},
	{"name": "Asparagus (fresh)", "score": 3},
	{"name": "Beetroot (fresh)", "score": 3},
	{"name": "Carrot (fresh)", "score": 3},
	{"name": "Cauliflower", "score": 3},
	{"name": "Corn (fresh)", "score": 3},
	{"name": "French beans", "score": 3},
	{"name": "Horseradish (canned)", "score": 3},
	{"name": "Mushroom (fresh)", "score": 3},
	{"name": "Onion", "score": 3},
	{"name": "Potato (unpeeled white)", "score": 3},
	{"name": "Peas (fresh)", "score": 3},
	{"name": "Pimiento (canned)", "score": 3},
	{"name": "Pumpkin", "score": 3},
	{"name": "Spinach (frozen)", "score": 3},
	{"name": "Tomato (fresh)", "score": 3},
	{"name": "Turnip", "score": 3},
	{"name": "Bean Sprouts", "score": 3},
	{"name": "Borlotti beans", "score": 3},
	{"name": "Brussels sprouts", "score": 3},
	{"name": "Cabbage - red", "score": 3},
	{"name": "Chickpeas", "score": 3},
	{"name": "Chives", "score": 3},
	{"name": "Choko", "score": 3},
	{"name": "Green Beans", "score": 3},
	{"name": "Green Peas", "score": 3},
	{"name": "Leek", "score": 3},
	{"name": "Mung bean sprouts", "score": 3},
	{"name": "Onion", "score": 3},
	{"name": "Potato (white with peel)", "score": 3},
	{"name": "Shallots", "score": 3},
	{"name": "Yellow split peas", "score": 3},
	{"name": "Asparagus (canned)", "score": 5},
	{"name": "Beetroot (canned)", "score": 5},
	{"name": "Corn (canned)", "score": 5},
	{"name": "Bok choy", "score": 5},
	{"name": "Choy sum", "score": 5},
	{"name": "Lettuce (other than iceberg)", "score": 5},
	{"name": "Maize", "score": 5},
	{"name": "Olives (black )", "score": 5},
	{"name": "Parsley", "score": 5},
	{"name": "Parsnip", "score": 5},
	{"name": "Potato (red)", "score": 5},
	{"name": "Pumpkin", "score": 5},
	{"name": "Snow peas (and sprouts)", "score": 5},
	{"name": "Sweet corn", "score": 5},
	{"name": "Sweet potato (yellow)", "score": 5},
	{"name": "Aubergine - peeled", "score": 5},
	{"name": "Beetroot", "score": 5},
	{"name": "Carrot", "score": 5},
	{"name": "Fresh Tomato", "score": 5},
	{"name": "Frozen Spinach", "score": 5},
	{"name": "Marrow", "score": 5},
	{"name": "Mushrooms", "score": 5},
	{"name": "Sprout", "score": 5},
	{"name": "Turnip", "score": 5},
	{"name": "Alfalfa", "score": 7},
	{"name": "Artichoke", "score": 7},
	{"name": "Broad beans", "score": 7},
	{"name": "Broccoli", "score": 7},
	{"name": "Chili (green and yellow)", "score": 7},
	{"name": "Corn (creamed)", "score": 7},
	{"name": "Cucumber", "score": 7},
	{"name": "Eggplant", "score": 7},
	{"name": "Fava beans", "score": 7},
	{"name": "Okra", "score": 7},
	{"name": "Spinach (fresh)", "score": 7},
	{"name": "Squash", "score": 7},
	{"name": "Sweet potato (white)", "score": 7},
	{"name": "Tomato (canned)", "score": 7},
	{"name": "Water chestnut", "score": 7},
	{"name": "Watercress", "score": 7},
	{"name": "Aubergine with peel", "score": 7},
	{"name": "Canned black olive", "score": 7},
	{"name": "Radish", "score": 7},
	{"name": "Sweet Potato", "score": 7},
	{"name": "Zucchini", "score": 7},
	{"name": "Capsicum (green)", "score": 9},
	{"name": "Champignon (canned)", "score": 9},
	{"name": "Chili (red)", "score": 9},
	{"name": "Chicory", "score": 9},
	{"name": "Courgette", "score": 9},
	{"name": "Endive", "score": 9},
	{"name": "Gherkin", "score": 9},
	{"name": "Mushroom (canned)", "score": 9},
	{"name": "Olives (green)", "score": 9},
	{"name": "Pepper (sweet)", "score": 9},
	{"name": "Radish", "score": 9},
	{"name": "Tomato (paste and sauce)", "score": 9},
	{"name": "Zucchini", "score": 9},
	{"name": "Hot pepper", "score": 9},
	{"name": "Peppers", "score": 9},
	{"name": "Tomato", "score": 9},
	{"name": "Water Chestnut", "score": 9},
	{"name": "Banana", "score": 1},
	{"name": "Pear (peeled)", "score": 1},
	{"name": "Canned Pear (in syrup, not juice)", "score": 1},
	{"name": "Lime", "score": 1},
	{"name": "Apple (golden and red delicious)", "score": 3},
	{"name": "Custard apple", "score": 3},
	{"name": "Fig", "score": 3},
	{"name": "Cherries (sour canned, morello)", "score": 3},
	{"name": "Grapes (green)", "score": 3},
	{"name": "Lemon (fresh)", "score": 3},
	{"name": "Mango", "score": 3},
	{"name": "Pawpaw", "score": 3},
	{"name": "Passion fruit", "score": 3},
	{"name": "Persimmon", "score": 3},
	{"name": "Pineapple juice", "score": 3},
	{"name": "Pomegranate", "score": 3},
	{"name": "Rhubarb", "score": 3},
	{"name": "Tamarillo", "score": 3},
	{"name": "Nashi Pears", "score": 3},
	{"name": "Papaya", "score": 3},
	{"name": "Apple (Jonathon)", "score": 5},
	{"name": "Apple (canned)", "score": 5},
	{"name": "Grapefruit juice", "score": 5},
	{"name": "Kiwi fruit", "score": 5},
	{"name": "Lychee", "score": 5},
	{"name": "Loquat", "score": 5},
	{"name": "Nectarine (fresh)", "score": 5},
	{"name": "Pear (with peel)", "score": 5},
	{"name": "Plum (fresh)", "score": 5},
	{"name": "Watermelon", "score": 5},
	{"name": "Apple - red delicious", "score": 5},
	{"name": "Canned or dried Fig", "score": 5},
	{"name": "Canned pear (in juice, not syrup)", "score": 5},
	{"name": "Custard apple", "score": 5},
	{"name": "Lemon", "score": 5},
	{"name": "Mango", "score": 5},
	{"name": "Persimmon", "score": 5},
	{"name": "Pomegranate", "score": 5},
	{"name": "Rhubarb", "score": 5},
	{"name": "Fresh Tomato", "score": 5},
	{"name": "Passion fruit", "score": 5},
	{"name": "Apple - all other varieties", "score": 7},
	{"name": "Avocado (fresh)", "score": 7},
	{"name": "Cherries (sweet)", "score": 7},
	{"name": "Fig (dried)", "score": 7},
	{"name": "Grapes (red)", "score": 7},
	{"name": "Grape juice", "score": 7},
	{"name": "Grape fruit", "score": 7},
	{"name": "Mandarin", "score": 7},
	{"name": "Mulberry", "score": 7},
	{"name": "Peach (fresh and canned)", "score": 7},
	{"name": "Tangelo", "score": 7},
	{"name": "Canned Morello cherries", "score": 7},
	{"name": "Cantaloupe", "score": 7},
	{"name": "Kiwi fruit", "score": 7},
	{"name": "Lychee", "score": 7},
	{"name": "Melons", "score": 7},
	{"name": "Nectarine", "score": 7},
	{"name": "Sugar banana", "score": 7},
	{"name": "Watermelon", "score": 7},
	{"name": "Apricot", "score": 9},
	{"name": "Blackberries", "score": 9},
	{"name": "Blueberries", "score": 9},
	{"name": "Boysenberries", "score": 9},
	{"name": "Cantaloupe Rockmelon", "score": 9},
	{"name": "Cherries - all other kinds", "score": 9},
	{"name": "Cranberry (sauce and canned)", "score": 9},
	{"name": "Currants", "score": 9},
	{"name": "Dates", "score": 9},
	{"name": "Grapes (fresh)", "score": 9},
	{"name": "Guava", "score": 9},
	{"name": "Loganberries", "score": 9},
	{"name": "Orange", "score": 9},
	{"name": "Pineapple", "score": 9},
	{"name": "Plum (canned)", "score": 9},
	{"name": "Prunes", "score": 9},
	{"name": "Raisons", "score": 9},
	{"name": "Raspberry", "score": 9},
	{"name": "Redcurrants", "score": 9},
	{"name": "Strawberries", "score": 9},
	{"name": "Sultanas", "score": 9},
	{"name": "Youngberry", "score": 9},
	{"name": "All dried Fruits", "score": 9},
	{"name": "Avocado", "score": 9},
	{"name": "Blackberry", "score": 9},
	{"name": "Blackcurrant", "score": 9},
	{"name": "Plum", "score": 9},
	{"name": "Rock melon", "score": 9},
	{"name": "Tangelo", "score": 9},
	{"name": "Tangerine", "score": 9},
	{"name": "Tomato", "score": 9},
	{"name": "Tomato Products", "score": 9},
	{"name": "Water chestnut", "score": 9},
	{"name": "Butter", "score": 1},
	{"name": "Canola Oil", "score": 1},
	{"name": "Margarine****", "score": 1},
	{"name": "Safflower Oil", "score": 1},
	{"name": "Soy Oil", "score": 1},
	{"name": "Sunflower Oil", "score": 1},
	{"name": "Ghee", "score": 3},
	{"name": "Almond Oil", "score": 5},
	{"name": "Corn Oil", "score": 5},
	{"name": "Peanut Oil", "score": 5},
	{"name": "Copha", "score": 7},
	{"name": "Sesame oil", "score": 7},
	{"name": "Walnut Oil", "score": 7},
	{"name": "Coconut Oil", "score": 9},
	{"name": "Olive Oil", "score": 9},
	{"name": "Cashews", "score": 1},
	{"name": "Poppy seeds", "score": 1},
	{"name": "All grains (except maize)", "score": 1},
	{"name": "BarleyBuckwheat", "score": 1},
	{"name": "Millet", "score": 1},
	{"name": "Oats (plain)", "score": 1},
	{"name": "Rice", "score": 1},
	{"name": "Rice cereals (plain)", "score": 1},
	{"name": "Rye", "score": 1},
	{"name": "Wheat", "score": 1},
	{"name": "Pecans", "score": 3},
	{"name": "Peanut butter", "score": 3},
	{"name": "Sesame seeds", "score": 3},
	{"name": "Hazelnuts", "score": 3},
	{"name": "Sunflower seeds", "score": 3},
	{"name": "Potato chips (plain)", "score": 3},
	{"name": "Cashews", "score": 3},
	{"name": "Sunflower seeds", "score": 3},
	{"name": "Coconut (desiccated)", "score": 5},
	{"name": "Brazil nuts", "score": 5},
	{"name": "Corn chips", "score": 5},
	{"name": "Popcorn", "score": 5},
	{"name": "Pumpkin seeds", "score": 5},
	{"name": "Taco shells", "score": 5},
	{"name": "Walnuts", "score": 5},
	{"name": "Peanut Butter", "score": 5},
	{"name": "Sesame seeds", "score": 5},
	{"name": "Apple chips (only if homemade from acceptable varieties of apples)", "score": 5},
	{"name": "Pine nuts", "score": 7},
	{"name": "Macadamia nuts", "score": 7},
	{"name": "Pistachio nuts", "score": 7},
	{"name": "Brazil nuts", "score": 7},
	{"name": "Breakfast cereals that include fruit, nuts, honey or coconutCorn/maize cereals", "score": 7},
	{"name": "Cornmeal", "score": 7},
	{"name": "Flavored breakfast cereals", "score": 7},
	{"name": "Maize", "score": 7},
	{"name": "Polenta", "score": 7},
	{"name": "Popcorn", "score": 7},
	{"name": "Popping corn", "score": 7},
	{"name": "Almonds", "score": 9},
	{"name": "Peanuts", "score": 9},
	{"name": "Chips and crackers (savory flavored)", "score": 9},
	{"name": "Chewing gum (all flavors)", "score": 9},
	{"name": "Fruit flavored candy, gelato, ices, popsicles, sherbet, sorbet, and sweets", "score": 9},
	{"name": "Licorice/liquorices (all flavors)", "score": 9},
	{"name": "Mint/peppermint/wintergreen flavored candy/sweets", "score": 9},
	{"name": "Pickles (and anything pickled)", "score": 9},
	{"name": "Garlic (fresh)", "score": 1},
	{"name": "Parsley", "score": 1},
	{"name": "Chives", "score": 1},
	{"name": "Coriander", "score": 1},
	{"name": "Salt", "score": 1},
	{"name": "Malt Vinegar", "score": 1},
	{"name": "Golden Syrup", "score": 1},
	{"name": "Maple Syrup (pure)", "score": 1},
	{"name": "Vinegar", "score": 3},
	{"name": "Soy sauce", "score": 3},
	{"name": "Saffron", "score": 3},
	{"name": "Tandoori spice powder", "score": 3},
	{"name": "Horseradish (canned)", "score": 3},
	{"name": "Vanilla", "score": 3},
	{"name": "Apple Butter (only if homemade from acceptable varieties of apples)", "score": 3},
	{"name": "Chives", "score": 3},
	{"name": "Fennel - dried", "score": 3},
	{"name": "Garlic", "score": 3},
	{"name": "Parsley (except Chinese parsley also known as coriander)", "score": 3},
	{"name": "Saffron", "score": 3},
	{"name": "Shallots", "score": 3},
	{"name": "Soy Sauce (if free of spices)", "score": 3},
	{"name": "Fennel", "score": 5},
	{"name": "Fresh Coriander Leaves (also known as Chinese parsley)", "score": 5},
	{"name": "Horseradish", "score": 5},
	{"name": "Mayonnaise", "score": 5},
	{"name": "Vegemite", "score": 7},
	{"name": "Vinegars (red and white wine, cider and others)", "score": 7},
	{"name": "All Spice", "score": 7},
	{"name": "Bay leaf", "score": 7},
	{"name": "Caraway", "score": 7},
	{"name": "Cardamom", "score": 7},
	{"name": "Cinnamon", "score": 7},
	{"name": "Cloves", "score": 7},
	{"name": "Coriander", "score": 7},
	{"name": "Gravy made from prepared mixes (i.e. stock cubes/bouillon/meat extracts/etc.)", "score": 7},
	{"name": "Ginger", "score": 7},
	{"name": "Mixed herbs", "score": 7},
	{"name": "Mustard", "score": 7},
	{"name": "Pimiento", "score": 7},
	{"name": "All spice", "score": 9},
	{"name": "Anise seed", "score": 9},
	{"name": "Cayenne", "score": 9},
	{"name": "Celery powder", "score": 9},
	{"name": "Cinnamon", "score": 9},
	{"name": "Cumin", "score": 9},
	{"name": "Curry powder", "score": 9},
	{"name": "Dill", "score": 9},
	{"name": "Fenugreek", "score": 9},
	{"name": "Five spice", "score": 9},
	{"name": "Garam masala", "score": 9},
	{"name": "Ginger", "score": 9},
	{"name": "Honey", "score": 9},
	{"name": "Jam", "score": 9},
	{"name": "Mace", "score": 9},
	{"name": "Mint", "score": 9},
	{"name": "Mixed herbs", "score": 9},
	{"name": "Mustard", "score": 9},
	{"name": "Oregano", "score": 9},
	{"name": "Paprika (hot)", "score": 9},
	{"name": "Paprika (sweet)", "score": 9},
	{"name": "Pepper", "score": 9},
	{"name": "Rosemary", "score": 9},
	{"name": "Sage", "score": 9},
	{"name": "Tarragon", "score": 9},
	{"name": "Turmeric", "score": 9},
	{"name": "Thyme", "score": 9},
	{"name": "Worcestershire sauce", "score": 9},
	{"name": "Basil", "score": 9},
	{"name": "Black pepper", "score": 9},
	{"name": "Chili flakes", "score": 9},
	{"name": "Chili Powder", "score": 9},
	{"name": "Cider Vinegar", "score": 9},
	{"name": "Commercial Gravies & Sauces", "score": 9},
	{"name": "Fish, meat, and tomato pastes", "score": 9},
	{"name": "Liquorices", "score": 9},
	{"name": "Marmite", "score": 9},
	{"name": "Nutmeg", "score": 9},
	{"name": "Peppermint", "score": 9},
	{"name": "Tabasco", "score": 9},
	{"name": "Vegemite and other Yeast Extracts****", "score": 9},
	{"name": "White pepper", "score": 9},
	{"name": "White Vinegar", "score": 9},
	{"name": "Wine Vinegar", "score": 9},
	{"name": "Beef", "score": 1},
	{"name": "Chicken", "score": 1},
	{"name": "Eggs", "score": 1},
	{"name": "Fish", "score": 1},
	{"name": "Lamb", "score": 1},
	{"name": "Organ meats", "score": 1},
	{"name": "Rabbit", "score": 1},
	{"name": "Sausage casing", "score": 1},
	{"name": "Scallops", "score": 1},
	{"name": "Tripe", "score": 1},
	{"name": "Veal", "score": 1},
	{"name": "Liver", "score": 3},
	{"name": "Prawns", "score": 3},
	{"name": "Shellfish", "score": 3},
	{"name": "Fish canned in an unacceptable oil and/or with seasonings added", "score": 7},
	{"name": "Processed luncheon meats (many are seasoned and thus contain salicylates)", "score": 9},
	{"name": "Seasoned meats (e.g. salami, sausages, frankfurters, and hotdogs", "score": 9},
	{"name": "Tea (all varieties)", "score": 9},
	{"name": "Liqueur", "score": 9},
	{"name": "Peppermint tea", "score": 9},
	{"name": "Port", "score": 9},
	{"name": "Rum", "score": 9},
	{"name": "Champagne", "score": 9},
	{"name": "Wines", "score": 9},
	{"name": "Cordials", "score": 9},
	{"name": "Butter", "score": 1},
	{"name": "Cream", "score": 1},
	{"name": "Cheese (not blue vein)", "score": 1},
	{"name": "Milk", "score": 1},
	{"name": "Yoghurt (natural only)", "score": 1},
	{"name": "Ice Cream ****", "score": 1},
	{"name": "Rice Milk", "score": 1},
	{"name": "Goat Milk", "score": 1},
	{"name": "Soy Milk ****", "score": 1},
	{"name": "Tofu", "score": 1},
	{"name": "Eggs", "score": 1},
	{"name": "Blue vein Cheese", "score": 5},
	{"name": "Arrowroot", "score": 1},
	{"name": "Corn starch (also known as corn flour in Australia)", "score": 1},
	{"name": "Golden Syrup", "score": 1},
	{"name": "Malt", "score": 1},
	{"name": "Malt extract", "score": 1},
	{"name": "Poppy seeds", "score": 1},
	{"name": "Rice Flour", "score": 1},
	{"name": "Rye Flour", "score": 1},
	{"name": "Sago", "score": 1},
	{"name": "Soy Flour", "score": 1},
	{"name": "Sugar", "score": 1},
	{"name": "Sugar (brown, castor, granulated, icing, powdered)", "score": 1},
	{"name": "Tapioca", "score": 1},
	{"name": "Wheat Flour", "score": 1},
	{"name": "Molasses", "score": 3},
	{"name": "Brown sugar", "score": 3},
	{"name": "Caramel", "score": 3},
	{"name": "Golden Syrup", "score": 3},
	{"name": "Malt Extract", "score": 3},
	{"name": "Molasses", "score": 5},
	{"name": "Raw Sugar", "score": 5},
	{"name": "Corn Syrup", "score": 7},
	{"name": "Golden syrup", "score": 1},
	{"name": "Maple syrup", "score": 1},
	{"name": "White sugar", "score": 1},
	{"name": "Carob", "score": 1},
	{"name": "Cocoa", "score": 1},
	{"name": "Homemade caramel", "score": 1},
	{"name": "Cocoa powder", "score": 1},
	{"name": "Carob powder", "score": 1},
	{"name": "Coffee (Decaf)", "score": 1},
	{"name": "Ovaltine", "score": 1},
	{"name": "Milk (goat and cow)", "score": 1},
	{"name": "Pear Juice (homemade)", "score": 1},
	{"name": "Soy milk", "score": 1},
	{"name": "Rice milk", "score": 1},
	{"name": "Gin", "score": 1},
	{"name": "Whiskey", "score": 1},
	{"name": "Vodka", "score": 1},
	{"name": "Chamomile tea", "score": 3},
	{"name": "Vodka", "score": 3},
	{"name": "Whiskey", "score": 3},
	{"name": "Gin", "score": 3},
	{"name": "Dandelion coffee", "score": 3},
	{"name": "Pear Juice (store bought)", "score": 3},
	{"name": "Coffee (instant)", "score": 5},
	{"name": "Rosehip tea", "score": 5},
	{"name": "Fruit herbal tea", "score": 5},
	{"name": "Brandy", "score": 5},
	{"name": "Vermouth", "score": 5},
	{"name": "Beer", "score": 5},
	{"name": "Cider", "score": 5},
	{"name": "Coco cola", "score": 5},
	{"name": "Rose hip tea", "score": 5},
	{"name": "Rose hip syrup", "score": 5},
	{"name": "Sherry", "score": 5},
	{"name": "Sherry", "score": 7},
	{"name": "Cointreau", "score": 7},
	{"name": "Tia Maria", "score": 7},
	{"name": "Fruit juices", "score": 7},
	{"name": "regular coffee", "score": 7},
	{"name": "all teas", "score": 7},
	{"name": "Cordials and fruit flavored drinks", "score": 7},
	{"name": "Liquor", "score": 7},
	{"name": "Port", "score": 7},
	{"name": "Wine", "score": 7},
	{"name": "Rum", "score": 7},
]